# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 01 - GGArtistry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project 01 - GGArtistry
  target 'Project 01 - GGArtistryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project 01 - GGArtistryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Pods library
  pod 'DynamicColor', '~> 3.2.1'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'

end
