# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnAPIClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnAPIClient
  pod 'Moya', '~> 4.4'
  pod 'SwiftyJSON'
end
